name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: '30 12 * * 1'
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  scan-scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://git.quad4.io/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: OSV scan
        run: bash scripts/osv_scan.sh

